### ISSUE TITLE
Error watching metadata: invalid character '<' looking for beginning of value - Windows server 

### ISSUE THREAD

**Issue by deepak-rxt** [GoogleCloudPlatform/guest-agent#364]
Getting the below error in all our Windows servers. Any specific version to install to fix the issue?
 
 `2024/01/30 16:13:53 GCEGuestAgent: Error watching metadata: invalid character '<' looking for beginning of value

2024/01/30 16:13:53 GCEGuestAgent: Metadata event watcher failed, ignoring: invalid character '<' looking for beginning of value

2024/01/30 16:13:53 GCEGuestAgent: Metadata event watcher failed, ignoring: invalid character 'M' looking for beginning of value

2024/01/30 16:13:53 GCEGuestAgent: Metadata event watcher failed, ignoring: invalid character 'M' looking for beginning of value

2024/01/30 16:13:53 GCEGuestAgent: Metadata event watcher failed, ignoring: invalid character 'M' looking for beginning of value

2024/01/30 16:13:53 GCEGuestAgent: Metadata event watcher failed, ignoring: invalid character 'M' looking for beginning of value`'

There is already a closed issue https://github.com/GoogleCloudPlatform/guest-agent/issues/320

**Comment by ChaitanyaKulkarni28** [comment]
Hi @deepak-rxt, what Guest Agent and Windows image version you're using?

**Comment by deepak-rxt** [comment]
Hey @ChaitanyaKulkarni28 , 

Edition	Windows Server 2022 Datacenter
Version	21H2
OS build	20348.2113

GCE Agent version 20231004.02

**Comment by ChaitanyaKulkarni28** [comment]
Is the error you're seeing consistent? If not, Guest Agent would retry connecting to MDS. 

Also, is there any change in behavior if you reboot your system.

**Comment by deepak-rxt** [comment]
Nope, errors are not consistent. haven't tried rebooting.

**Comment by ChaitanyaKulkarni28** [comment]
@deepak-rxt are you seeing these errors only on instance startup or at random times?

**Comment by outbackStack** [comment]
same issues with Debian Server came out of no where. 
```
severity: "ERROR"
sourceLocation: {
  file: "metadata.go"
  function: "github.com/GoogleCloudPlatform/guest-agent/google_guest_agent/events/metadata.(*Watcher).Run"
  line: "68"
}
jsonPayload: {
  localTimestamp: "2024-04-08T19:17:25.3397+10:00"
  message: "Error watching metadata: invalid character '<' looking for beginning of value"
  omitempty: null
}
```

**Comment by outbackStack** [comment]
```
{
  "jsonPayload": {
    "omitempty": null,
    "message": "Metadata event watcher failed, ignoring: invalid character 'M' looking for beginning of value",
    "localTimestamp": "2024-04-08T19:17:25.8373+10:00"
  },
  "sourceLocation": {
    "file": "main.go",
    "line": "225",
    "function": "main.runAgent.func1"
  },
  "receiveTimestamp": "2024-04-08T09:17:26.414441172Z"
}
```

**Comment by ChaitanyaKulkarni28** [comment]
This issue is fixed in Guest Agent and should be available soon. I will update it here once the new version is released.

Regardless of these error logs, it should not impact any functioning of the Guest Agent at all as agent will retry all transient errors. This is just the mishandling of the error status returned by Metadata server to Guest Agent.

**Comment by mschewe** [comment]
@ChaitanyaKulkarni28 Is there any news on when the update will be published? Last week (7 days), we received around 28K log messages from this, of which 26 were error level.

**Comment by ChaitanyaKulkarni28** [comment]
Fix is present in current latest guest agent version `20240808.00`. Note that we will still see the error in such situations but it will be 503 MDS unavailable or something and not this weird `invalid character 'M' looking for beginning of value` message

**Comment by smallwat3r** [comment]
We're using App Engine flex with a custom runtime, and we're seeing this issue. We are not managing the guest-agent package in our custom docker env.

Is there a way for us to force the update of guest-agent used by AE to a newer version?

**Comment by d-croe** [comment]
we still see the same error in version: "20240927.00" in managed kubernetes cluster and the node running: 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=9
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=18244.291.9
GOOGLE_RELEASE=18244.291.9

**Comment by d-croe** [comment]
any updates on this?
